name: Publish Beta

on:
  push:
    branches: [ beta ]

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 12.x
      TITLE: TechZone Automation
      ANALYTICS_ID: ""

    steps:
      - uses: actions/checkout@v2
      - name: generate site
        uses: ./.github/actions/
      - name: Set CNAME
        run: sudo chmod 777 ./public/CNAME && echo "beta.cloudnativetoolkit.dev" > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: cloud-native-toolkit/ibm-garage-developer-guide-beta
          publish_branch: master
          publish_dir: ./public
